# use g++ compiler
CXX=g++

# flag specifications for release and debug
CXXFLAGS?=-Wall -pedantic -std=c++11
RELEASEFLAGS?=$(CXXFLAGS) -O3
DEBUGFLAGS?=$(CXXFLAGS) -O0 -g

# relevant constants
GLOBAL_DEPS=main.cpp common.cpp common.h
EXE_PREFIX=coatran
CONSTANT=constant
CONSTANT_EXE=$(EXE_PREFIX)_$(CONSTANT)
CONSTANT_DEBUG=$(CONSTANT)_debug
CONSTANT_DEBUG_EXE=$(EXE_PREFIX)_$(CONSTANT_DEBUG)
EXPGROWTH=expgrowth
EXPGROWTH_EXE=$(EXE_PREFIX)_$(EXPGROWTH)
EXPGROWTH_DEBUG=$(EXPGROWTH)_debug
EXPGROWTH_DEBUG_EXE=$(EXE_PREFIX)_$(EXPGROWTH_DEBUG)
EXES=$(CONSTANT_EXE) $(CONSTANT_DEBUG_EXE) $(EXPGROWTH_EXE) $(EXPGROWTH_DEBUG_EXE)

# compile all executables
all: $(CONSTANT) $(EXPGROWTH)
debug: $(CONSTANT_DEBUG) $(EXPGROWTH_DEBUG)

# constant population size
$(CONSTANT): $(GLOBAL_DEPS)
	$(CXX) $(RELEASEFLAGS) -o $(CONSTANT_EXE) $(GLOBAL_DEPS)
$(CONSTANT_DEBUG): $(GLOBAL_DEPS)
	$(CXX) $(DEBUGFLAGS) -o $(CONSTANT_DEBUG_EXE) $(GLOBAL_DEPS)

# exponential population size growth
EXPGROWTH_FLAG=-DEXPGROWTH
$(EXPGROWTH): $(GLOBAL_DEPS)
	$(CXX) $(RELEASEFLAGS) $(EXPGROWTH_FLAG) -o $(EXPGROWTH_EXE) $(GLOBAL_DEPS)
$(EXPGROWTH_DEBUG): $(GLOBAL_DEPS)
	$(CXX) $(DEBUGFLAGS) $(EXPGROWTH_FLAG) -o $(EXPGROWTH_DEBUG_EXE) $(GLOBAL_DEPS)

# clean things up
clean:
	$(RM) $(EXES) *.o